# Generated by Django 5.0.6 on 2024-05-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_delete_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
