# Generated by Django 5.0.6 on 2024-05-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': False},
        ),
    ]
